# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 349)
        self.labelresponsive = QtWidgets.QLabel(parent=Dialog)
        self.labelresponsive.setGeometry(QtCore.QRect(90, 60, 591, 181))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.labelresponsive.setFont(font)
        self.labelresponsive.setObjectName("labelresponsive")
        self.lineEditName = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditName.setGeometry(QtCore.QRect(680, 130, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setObjectName("lineEditName")
        self.buttonSubmit = QtWidgets.QPushButton(parent=Dialog)
        self.buttonSubmit.setGeometry(QtCore.QRect(400, 217, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.buttonSubmit.setFont(font)
        self.buttonSubmit.setObjectName("buttonSubmit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelresponsive.setText(_translate("Dialog", "enter your name"))
        self.buttonSubmit.setText(_translate("Dialog", "submit"))
